### ISSUE TITLE
How to reload data in  the mode of "reduced feature"

### ISSUE THREAD

**Issue by linshuliang** [tensorflow/tensorboard#2542]
I haven't install TensorFlow, but I want to use Tensorboard to display the data logged with TensorboardX.

```
TensorFlow installation not found - running with reduced feature set.
```

It can't reload data automatically,  unless I shut down tensorboard `Ctrl + C` and restart again.

How can I activate the automatically reload?

**Comment by nfelt** [comment]
Duplicate of #2441

**Comment by nfelt** [comment]
This bug has been fixed, but so far it's only in our nightly releases, so you'd need to uninstall `tensorboard` and instead install `tb-nightly`.  See #2441 for details.

**Comment by linshuliang** [comment]
I have tried this method, but i doesn't work.

There is no log info printed in terminal, is that mean "The frontend does't send request of reloading data"?

Look forward to your kind reply.

**Comment by nfelt** [comment]
If you're still seeing this issue, can you provide the details that we ask for in our issue template?  You can see that here: https://github.com/tensorflow/tensorboard/issues/new?assignees=&labels=&template=bug_report.md&title=

In particular, we would need to know exactly which version of `tb-nightly` you installed, and instructions that reproduce the issue (e.g. something like "run these lines of code to emit the summaries, launch TensorBoard using this command line, rerun the code to emit more data, observe that TensorBoard doesn't show the new data").

**Comment by cswwp** [comment]
Hi, @nfelt, i have install tb_nightly (version 2.1.0a20191021), and restart tensorboard --log_dir target dir,  and it still shows that "TensorFlow installation not found - running with reduced feature set." I'm confused

**Comment by 07Agarg** [comment]
Hi, I have installed the following versions of tb-nightly
tb-nightly==2.2.0a20200106
tblib==1.4.0
Still facing the same error of "TensorFlow installation not found - running with reduced feature set."

Should I install tensorflow using conda commands?
