### ISSUE TITLE
path /[[_dataImageSrc]] not found, sending 404

### ISSUE THREAD

**Issue by AnneMaelle** [tensorflow/tensorboard#982]
Hi,

I was trying to run TensorBoard example : mnist_with_summaries.py and when I tried to open an instance of TensorBoard I got this : 
command:
`tensorboard --logdir=/output --host localhost --port=6006`

output:
`TensorBoard 1.5.1 at http://localhost:6006 (Press CTRL+C to quit)`
`W0219 15:12:02.944875 Thread-1 application.py:273] path /[[_dataImageSrc]] not found, sending 404`

When I try to open http://localhost:6006, my browser crash.

I am on Ubuntu 16.04, with tensorflow GPU and the 1.5.1 version

**Comment by nfelt** [comment]
What browser were you using?  Also, what exactly do you meant by crash - did the whole browser quit unexpectedly?  Or just the page/tab crashed?

If you can try running tensorboard again with a non-existent log directory, like `--logdir=/tmp/fakelogdir` then can you see if it still crashes in that case or if it loads normally?  If you're able to load the page and check your browser's javascript console (e.g. the Chrome developer tools javascript console) for any messages and post those here, that would also be useful in debugging.

**Comment by AnneMaelle** [comment]
I am using Mozilla Firefox, and the whole browser crash whenever I try to access localhost. Changing directory doesn't change anything.

The crash report mentions :
```
MozCrashReason: MOZ_CRASH(GFX: Unexpected GLSL version.)
Notes: Ubuntu 16.04.3 LTSFP(D00-L1000-W00000000-T000) OpenGL: NVIDIA Corporation -- GeForce GT 750M/PCIe/SSE2 -- 4.6.0 NVIDIA 390.30 -- texture_from_pixmap
```

I tried it on Chrome and it worked, thank you for your help !

**Comment by nfelt** [comment]
Hmm, yeah it looks like maybe a WebGL + Firefox issue - I found this bug that's possibly relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1382358

You might try updating either Firefox or your nvidia GPU drivers but that's about all I would be able to suggest.

Glad it's working in Chrome at least!  If you're still seeing the 404 error for "path /[[_dataImageSrc]]" not found I'd maybe try updating to the very latest TensorBoard via

```bash
pip uninstall tensorflow-tensorboard
pip install tensorboard
```

That should put you on TensorBoard 1.6.0.  If the 404 is still happening on that version, let us know and we'll investigate further.

**Comment by nfelt** [comment]
One thing to try might be changing the relevant `src` attributes to bind using `src$="[[_name]]"` rather than `src=` - see this section for details: https://www.polymer-project.org/1.0/docs/devguide/data-binding#attribute-binding

I'm not sure if that would actually fix this; the page doesn't mention `src` as a native property that requires attribute binding.  But since it is similar to `href` which is so mentioned, that might be worth trying.

Since it sounds like so far this just produces 404s on the console/log and doesn't actually impair function, we may not have time to look into this further for a while, but if somebody is motivated to fix this we'll happily take a PR.

**Comment by keihiromasa** [comment]
Hi.

I got the same issue, having “W0219 15:12:02.944875 Thread-1 application.py:273] path /[[_dataImageSrc]] not found, sending 404” and the firefox tab crushed(showing white page, and got some script error).

But I realized that firedox update has been downloaded, and when I applied the update, error doesn’t occur anymore.

Hope this info helps.

**Comment by stephanwlee** [comment]
PR #1315 should fix the issue. Please reopen the issue if a next release does not address the issue. Thank you!

**Comment by miracode2033** [comment]
I also have the same problem even though Tensorboards is blaming my CPU ...

![screenshot from 2018-10-08 06-54-02](https://user-images.githubusercontent.com/39874132/46591945-04a49e00-cac7-11e8-87b2-33071b51965c.png)

**Comment by stephanwlee** [comment]
Hi @miracode2033, it should be fixed in 1.10 or 1.11. You seem to be using 1.7.0

**Comment by miracode2033** [comment]
Thank you @stephanwlee  Let me check it out.

**Comment by mammadjv** [comment]
@fishguysword Switched to chromium and solved my problem ;)

**Comment by kirk86** [comment]
Hi @stephanwlee, I'm using tensorboard 1.11 and still get the same error:
![image](https://user-images.githubusercontent.com/2902390/47966316-ea6bca80-e048-11e8-8d75-351b979f1453.png)

**Comment by stephanwlee** [comment]
@kirk86 I believe those have been addressed in #1505 and is part of 1.12 release. Please try to upgrade :)

**Comment by stephanwlee** [comment]
I meant TensorBoard 1.12. https://pypi.org/project/tensorboard/1.12.0/

**Comment by bwang12** [comment]
I am using TensorBoard 1.12.2 and I am receiving the same error. I should add that I am using a workspace machine that I do have admin access to. 

What's different is that Chrome (Version 71.0.3578.98 (Official Build) (64-bit)) refuses to even connect to TensorBoard, giving a This site can't be reached error. 
On Internet Explorer (Version: 11.0.9600.19236CO), the page name would show up as TensorBoard but nothing is displayed in the body. 

And only when trying to access TensorBoard on Internet Explorer would result in new error log in cmd window:

(base) C:\Users\bwang>tensorboard --logdir =/tmp/summaries
TensorBoard 1.12.2 at http://PS-TRSPARE19:6006 (Press CTRL+C to quit)
W0208 11:28:28.265311 Thread-2 application.py:309] path /[[_traceDataUrl]] not f
ound, sending 404
W0208 11:28:28.265311  9252 application.py:309] path /[[_traceDataUrl]] not foun
d, sending 404

**Comment by hhsinhan** [comment]
maybe you need to type a dot before the slash
tensorboard --logdir=./output --host localhost --port=6006

**Comment by huxl5** [comment]
you can try to use Chrome
